### PR TITLE
Not using onFinished anymore, just onHeaders

### PR DESCRIPTION
**Pull request by idanstark42**

### CODE REVIEW

**Comment by alanggreen** [comment]
Will this require an update to all the modules? I presume so

**Comment by idanstark42** [comment]
There doesn't seem to be a problem with most modules, so no. But just in case I would do it anyway

**Comment by taltaub22** [comment]
@idanstark42 why this change is needed?

**Comment by idanstark42** [comment]
For some reason, probably incompatibilty of updated packages (since we're using two different packages here, `on-headers` and `on-finish`), the `onFinish` callback is called before the `onHeaders` callback. It's way more logical to chose one of them and go with it. I decided on `on-headers`, since it has a better support system and community.

**Pull request closed without merging**
