### PR TITLE
Fixing problem with setting the log-level by name

### PR DESCRIPTION
**Pull request by 2roy999**
Also adding codecov

### CODE REVIEW

**Review by idanstark42 — COMMENTED** [review]
Can you explain the changes in the test commands? Why do we need both codecov and nyc? And where is the requirement for 90% coverage?

**Comment by 2roy999** [comment]
nyc creates the coverage stats codecov is for tracking and visualizing it uses the report created by the nyc.
The requirement is moved to codecov, you can see in ms-configuration that the last pull request have a check of codecov like the check of appveyor. (This pr don't have that check because I opened it before I defined codecov)

**Comment by idanstark42** [comment]
Ok, so just add it here as well and make sure the build passes

**Comment by 2roy999** [comment]
@idanstark42 fixed it, as you can see above there is the codecov report of the coverage and also a required check inside github.

**Comment by idanstark42** [comment]
It says "No report found for this commit", but it still passes?

**Comment by 2roy999** [comment]
It's a base report (meaning on the master branch). The base report will be created after the merge you can click on the branches to see the report for this pr

**Review by idanstark42 — APPROVED** [review]

**Pull request merged**
